# Generated by Django 3.2.5 on 2021-07-28 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='reason',
            field=models.CharField(choices=[('a', 'Job Offer'), ('b', 'Other')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
