# Generated by Django 3.2.5 on 2021-08-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='my_response',
            field=models.BooleanField(default=False, verbose_name='Did I response'),
        ),
    ]
